-- ===========================================
-- 구글 헤드라인 RSS 아카이브용 테이블 정의 (MariaDB 기준)
-- 앱을 실행하기 전에 아래 DDL 을 MariaDB 에 그대로 실행하면 됩니다.
-- ARTICLE_LINK + PUB_DATE 조합에 UNIQUE 제약을 걸어 중복 저장을 방지합니다.
-- ===========================================
CREATE TABLE IF NOT EXISTS HEADLINE_NEWS (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PUB_DATE DATETIME NOT NULL,
    PUB_DATE_RAW VARCHAR(100),
    ARTICLE_TITLE VARCHAR(500) NOT NULL,
    ARTICLE_LINK VARCHAR(1000) NOT NULL,
    PRESS_NAME VARCHAR(200) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY UX_HEADLINE_NEWS (ARTICLE_LINK, PUB_DATE)
);
