-- 네이버 뉴스 검색 결과를 저장하기 위한 테이블 정의 (MySQL/MariaDB 호환)
CREATE TABLE IF NOT EXISTS news_articles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(500) NOT NULL,
    originallink VARCHAR(1000),
    link VARCHAR(1000),
    description TEXT,
    pub_date DATETIME,
    reg_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_news_link UNIQUE (link),
    CONSTRAINT uk_news_originallink UNIQUE (originallink)
);

-- 구글 뉴스 헤드라인 RSS를 통해 수집한 기사 정보를 저장하는 테이블
CREATE TABLE IF NOT EXISTS NEWS_GOOGLE_HEADLINE (
    ID BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TOPIC_GUID VARCHAR(255) NOT NULL,
    TOPIC_TITLE VARCHAR(500) NOT NULL,
    TOPIC_LINK VARCHAR(1000) NOT NULL,
    TOPIC_SOURCE_NAME VARCHAR(200) NULL,
    TOPIC_SOURCE_URL VARCHAR(500) NULL,
    TOPIC_PUB_DATE DATETIME NOT NULL,
    ARTICLE_ORDER INT NOT NULL,
    ARTICLE_TITLE VARCHAR(500) NOT NULL,
    ARTICLE_URL VARCHAR(1000) NOT NULL,
    ARTICLE_PRESS_NAME VARCHAR(200) NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    CONSTRAINT UK_NEWS_GOOGLE_ARTICLE_URL UNIQUE (ARTICLE_URL),
    INDEX IDX_NEWS_GOOGLE_PUBDATE (TOPIC_PUB_DATE),
    INDEX IDX_NEWS_GOOGLE_PRESS (ARTICLE_PRESS_NAME),
    INDEX IDX_NEWS_GOOGLE_TOPIC (TOPIC_GUID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
